language: objective-c

global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8

osx_image: xcode7.3

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild clean build test -project Fizzbuzz/Fizzbuzz.xcodeproj -scheme FizzbuzzTests -sdk "iphonesimulator9.3" -destination "OS=9.3,name=iPhone 6S Plus" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c;
